### ISSUE TITLE
CSS conflicts in user interface and e-mail previews.

### ISSUE THREAD

**Issue by JontyNewman** [roundcube/roundcubemail#5891]
We have been experiencing issues with e-mails being rendered in the classic skin that happen to contain elements with the ID `compose-container`.

Because the CSS of the skin contains the following rule, any block elements with the attribute `id="compose-container"` in a previewed e-mail will overlap:

```css
#compose-container {
	position: absolute;
	top: 0;
	left: 205px;
	right: 0;
	bottom: 0;
	margin: 0;
}
```

Ideally, e-mails shouldn't be containing multiple tags with the same ID. However, this is not within the recipient's control. Therefore, perhaps efforts should be made to ensure that the styling of a Roundcube skin will not conflict with the IDs and classes of elements within HTML e-mails.
