### ISSUE TITLE
German "Settings" in Elastic skin

### ISSUE THREAD

**Issue by thueske** [roundcube/roundcubemail#6392]
Hey guys,

I've tested the elastic skin which looks really nice - i like! :)

One thing is a bit confusing I think:
![german_settings](https://user-images.githubusercontent.com/436986/44074034-55ff7c8a-9f97-11e8-9b19-25189b63e7bd.png)

It is possible to set a new default size for the menu or to rename "Einstellungen" into "Optionen"?

Thanks!

**Comment by alecpl** [comment]
This could be fixed with following css code:
```css
@media screen and (min-width: @screen-width-medium) {
    html[lang=de] {
        body > #layout > .menu,
        #taskmenu a,
        #taskmenu a:before {
            width: 5.5rem;
        }
    }
}
```
but I don't like this solution.
