### ISSUE TITLE
Elastic: (wish) use bold to signal that a message is unread in thread mode

### ISSUE THREAD

**Issue by icefo** [roundcube/roundcubemail#7229]
hello,

Would you consider using bold for that ? I disabled thread view by default because people complained that unread messages were hard to spot in thread view. Using bold makes it much easier.

I edited styles.css to test this (monitoring just panicked on reboot) :

![image](https://user-images.githubusercontent.com/7746352/74873431-7baaa180-535f-11ea-9482-ff36046217fa.png)

It's also more visually consistent with the styling of an unread message without reply.

 I replaced
```css
.messagelist tr.unroot td.subject a {
 text-decoration:underline;
}
```
with
```css
.messagelist tr.unroot td.subject a {
 text-decoration:underline;
 font-weight:bold
}
```
