### ISSUE TITLE
Mails print on multiple pages

### ISSUE THREAD

**Issue by FreekBloemhof** [roundcube/roundcubemail#7604]
When printing an (HTML) e-mail it always prints on multiple pages. 

The browser seems to split it in multiple pages by dividing the message-header and message-content div's.

Also the lines are to wide, so the text runs out the margin's of the printer.

This happens in Chrome and Edge (Chromium). Also multiple print-setups tested.

**Comment by alecpl** [comment]
Which skin? Could you try with a different skin?

**Comment by FreekBloemhof** [comment]
Good question. Did some testing with different skins, it happens on the Classic, Elastic and Larry skin (those are all available).

**Comment by FreekBloemhof** [comment]
[Roundcube printissue.zip](https://github.com/roundcube/roundcubemail/files/5227305/Roundcube.printissue.zip)

I was able to find an mail with almost no content, removed all privacy information from it and saved it (using Edge Chromium). Attached the result to this post.

**Comment by dddns** [comment]
@alecpl , in my case, in classic theme or elastic, had the same behavior in last chrome

**Comment by smares** [comment]
I can confirm this issue, although it only happens with certain messages. I can provide you a mail where this occurs with the Elastic skin. To which address should I send you the mail source?

**Comment by alecpl** [comment]
I'll need a message source. Send it to test at alec.pl.

**Comment by FreekBloemhof** [comment]
> I'll need a message source. Send it to test at alec.pl.

It is attached to my post from 5 days ago.

**Comment by alecpl** [comment]
@FreekBloemhof I need the message source, not the HTML of the Roundcube window. That will be easier for me.

**Comment by alecpl** [comment]
I received one sample. I can confirm the issue. From what I've found for now the problem is with this css chunk, which is part of the message: 
```css
@page WordSection1 {size:612.0pt 792.0pt; margin:70.85pt 3.0cm 70.85pt 3.0cm;}
div.WordSection1 {page:WordSection1;}
```
After Roundcube css parser the output is:
```css
@page WordSection1 {size:612.0pt 792.0pt; margin:70.85pt 3.0cm 70.85pt 3.0cm;}
#message-htmlpart1 div.rcmBody div.v1WordSection1 {page:WordSection1;}
```
I'm not yet sure what the proper fix (workaround) would be. For example removing the last css rule fixes the issue. Could you confirm that this is the same issue for all of you guys?
