### ISSUE TITLE
Oauth error, relative path to .js and .css files

### ISSUE THREAD

**Issue by jtuta** [roundcube/roundcubemail#8144]
Hi,

I was testing 1.5-rc and its OAuth2 functionality to replace my custom implementation discussed in #6933 . While testing I have come across some errors when for this or other reason OAuth2 login didn't went through. Ok, the causes of those errors were mine and fixed, but there is one UX problem when such error occurs. 

On error, you land on url like: roundcube/index.php/login/oauth , which displays login form and wants to show error. Because all the .js and .css files are linked relatively they do not load properly, as they are being loaded from:
-  roundcube/index.php/login/skins/elastic/deps/bootstrap.min.css
- roundcube/index.php/login/program/js/jquery.min.js
- etc.

As none of .js and .css files are loaded the result is:
![image](https://user-images.githubusercontent.com/15046120/127009359-242b8c46-2ddf-4b63-9853-4e402b59e2fe.png)

but should be:
![image](https://user-images.githubusercontent.com/15046120/127009847-9add0f61-7e90-4768-a1d2-3f10bf749daa.png)

correct loading of js and css in the second case was made with dirty fix in config.php:
```
if(preg_match('/\/index\.php\/login\//', $_SERVER['PHP_SELF']) && $_SERVER['PHP_SELF'] != '/index.php/login/oauth') {
    header('Location: ' . str_replace('/index.php/login/', '/', $_SERVER['PHP_SELF']));
    die;
}
```

**Comment by thomascube** [comment]
This was supposed to be fixed in 8fdf37bf21. Maybe some other constellation of PHP ENV variables...

**Comment by jtuta** [comment]
Hi,

I rechecked. I used docker image `roundcube/roundcubemail:1.5-rc-apache` with more or less standard config and no special plugins ( only: archive', 'zipdownload').

Only confing entry "out of the ordinary" is `$config['use_https'] = true;`. I use it because I use [traefik](https://hub.docker.com/_/traefik) for http(s) request routing and ssl offloading. Therefore after traefik, there is http request from traefik to roundcube (no ssl here), and i need this config in order for the OAuth2 redirect url to be https://... not http://... (as roundcube 'thinks' it is accessed via http).

My deployment is roundcube directly deployed to subdomain (no addiional path): e.g. `https://roundcube.domain.com/`.

`if` condition in [commit 8fdf37b](https://github.com/roundcube/roundcubemail/commit/8fdf37bf21b8459d2504bfb9fdcb284049774807#diff-90d47c156392db4aa87ee7cb3716224aa015ca2477c1c75410ed06d8708d9b93R190) evaluates to `true`, therefore line191 executes. 

before line 191 therefore `$path` is empty string, and `$this->app->url([], true)` is `"/?_task=login"`, therefore also after line 191 `$path` is still an empty string.

I'd assume this in not correct? What  should in this case `$this->app->url([], true)` evaluate to?

**Comment by jtuta** [comment]
Sorry, 3rd comment in a row. After thinking for a bit, maybe `'/\/?\?_task=[a-z]+/'` should be changed to `'/?\?_task=[a-z]+/'`, as currently:

-  if roundcube is deployed to path like site.com/roundcube, path in line 191 becomes `'roundcube'`, therefore it is not empty string and function doesn't return in line 195.
- if roundcube is deployed to path like roundcube.site.com, path in line 191 is empty string, therefore function returns in line 195.

with my proposed "fix":

-  if roundcube is deployed to path like site.com/roundcube, path in line 191 becomes `'roundcube/'`, therefore it is not empty string and function doesn't return in line 195.
- if roundcube is deployed to path like roundcube.site.com, path in line 191 is `'/'`, therefore function does not return in line 195.

double slashes are then handled in line 203, where rtrim function is used....

**Comment by alecpl** [comment]
Confirmed. This can be easily reproduced. Works with `http://localhost/rc/index.php/login`, but it does not with `http://localhost/index.php/login`.

**Comment by arunodhayam1998** [comment]
Hi all, I have integrated keycloak with Roundcube(roundcube/roundcubemail:1.5-beta-apache) both are in docker. Keycloak is hosted under https://key.domain.com and the Roundcube is hosted under https://mail.domain.com. I didn't give any IMAP and SMTP configurations to RoundCube webmail. I have created users in keycloak. But can't log in with keycloak created user to Roundcube webmail.

**Comment by arunodhayam1998** [comment]
**Docker-compose file** 
    version: '2'

    services:
    roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb_1.5

    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 34013:5432
      - 33009:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail

    roundcubemail:
    image: roundcube/roundcubemail:1.5-beta-apache
    container_name: roundcubemail_1.5

    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 9005:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.example.org
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.example.org


**Roundcube configurations**
![Screenshot from 2021-11-20 14-23-37](https://user-images.githubusercontent.com/71403617/142726204-bd13e791-cf80-41ca-bdfe-c21ab31e6bb8.png)

**Keycloak configuration**
![Screenshot from 2021-11-20 14-24-45](https://user-images.githubusercontent.com/71403617/142726227-85c76f52-5014-4c33-8c6a-68720d9bab0a.png)

![Screenshot from 2021-11-20 14-25-02](https://user-images.githubusercontent.com/71403617/142726231-829b5b79-934c-4891-86d7-6ab6dc398887.png)

**Comment by jtuta** [comment]
Huh, after your first comment i suspected, but now it is clear that you are far from working system, as you do not have mailserver configured at all. 

Either you thaught that roundcube is "whole" mailserver or you have left out every pice of information hinting at working mailserver...

You need mailserver where roundcube would connect to (imap + smtp) - eg. Dovecot + postfix, etc. As far as I know you will need quite some configuration as usually such systems are not configured for oauth authenication out of the box. For a simple basic docker based mailserver you can start playing with https://github.com/docker-mailserver/docker-mailserver but as said, i think that you will have to configure dovecot by yourself: https://doc.dovecot.org/configuration_manual/authentication/oauth2/

Also your comment are offtopic to the issue, such comments make difficult to track issues in such projects.

**Comment by arunodhayam10d** [comment]
I have keycloak and the Roundcube both are in Docker and hosted under the domain https://keycloak.com and https://roundcube.com
I have integrated the keycloak with Roundcube and done the IMAP and SMTP server configurations.
I can able to log in to Roundcube with my mail server users with help of IMAP and SMTP.
I have created the users in Oauth(keycloak), But I can't log in with Oauth(keycloak) created user.
While logging in with Keycloak created users, It shows Login Failed

**Comment by arunodhayam10d** [comment]
```
version: '2'

services:
  roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb_1.5
    restart: unless-stopped
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 34013:5432
      - 33009:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail

  roundcubemail:
    image: roundcube/roundcubemail:1.5-beta-apache
    container_name: roundcubemail_1.5
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 9005:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver.mydomain.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993  
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mailserver.mydomain.com
      - ROUNDCUBEMAIL_SMTP_PORT=465 
```
This is my docker-compose.yml file pls help this
