### ISSUE TITLE
Can't Login With Oauth(KeyCloak) Created User

### ISSUE THREAD

**Issue by arunodhayam10d** [roundcube/roundcubemail#8340]
I have keycloak and the Roundcube both are in Docker and hosted under the domain https://keycloak.com and https://roundcube.com
I have integrated the keycloak with Roundcube and done the IMAP and SMTP server configurations. 
I can able to log in to Roundcube with my mail server users with help of IMAP and SMTP.
I have created the users in Oauth(keycloak), But I can't log in with Oauth(keycloak)  created user.
While logging in with Keycloak created users, It shows Login Failed

**Comment by alecpl** [comment]
Sorry, but this is not a support forum.

**Comment by arunodhayam10d** [comment]
```
version: '2'

services:
  roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb_1.5
    restart: unless-stopped
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 34013:5432
      - 33009:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail

  roundcubemail:
    image: roundcube/roundcubemail:1.5-beta-apache
    container_name: roundcubemail_1.5
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 9005:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver.mydomain.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993  
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mailserver.mydomain.com
      - ROUNDCUBEMAIL_SMTP_PORT=465 
``` 

This is my Docker-compose.yml file
