### ISSUE TITLE
Custom config is not used within the docker container

### ISSUE THREAD

**Issue by TheZoker** [roundcube/roundcubemail#8636]
I run roundcube 1.6 within docker using the following compose file:
```yml
version: '3.8'
services:
  roundcube:
    image: roundcube/roundcubemail
    container_name: Roundcube
    restart: always
    ports:
      - 80:80/tcp
    volumes:
      - ~/files/roundcube/config:/var/roundcube/config
      - ~/files/roundcube/sqlite:/var/roundcube/db
    environment:
      ROUNDCUBEMAIL_DB_TYPE: sqlite
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://example.com
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: tls://example.com
      ROUNDCUBEMAIL_SMTP_PORT: 587
```

Within the `files/roundcube/config` folder I have a file called `config.custom.inc.php` containing the following content:
```php
<?php

$config['skin_logo'] = 'https://example.com/logo.png';
$config['product_name'] = 'example.com';
```

While the sqlite volume works without any issue, the config volume does not work and the login page still looks like the default one:

![image](https://user-images.githubusercontent.com/1368405/181729846-b614d0d7-0491-43fe-8659-3db1a078bed5.png)

How can I debug this? Why is the config file not recognized by roundcube?
