### ISSUE TITLE
Bootstrap css global rule sometimes cause conflict with the email css

### ISSUE THREAD

**Issue by tpayen** [roundcube/roundcubemail#9727]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Hi Alec
In the boostrap.min.css there is a global rule 
```css
*, ::after, ::before {
  box-sizing: border-box;
}
```
so this rule also impact the display of an email. 
Most of the time there no issue with this rule but sometimes with advanced communicational email, this rule broke the email content.

Maybe we could add a rule like 
```css
#messagebody *, 
#messagebody ::after, 
#messagebody ::before {
  box-sizing: initial;
}
```
to avoid problems like that ?

### What browser(s) are you seeing the problem on?

Chrome, Edge, Firefox

### What version of Roundcube are you using?

1.6.9
